batch_size: 4
epoch: 200
learning_rate: 1e-3
gpu: 1
num_point: 1024
optimizer: Adam
weight_decay: 1e-4
normal: True
set_size: 10

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/cls/10/${model.name}

  sweep:
    dir: log/cls/10
    subdir: ${model.name}
